### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by andrew6850** [irothschild/stefuna#10]
Hi,
Stefuna looks like a great project!  I tried a very basic configuration but got the following error.  My Stefuna configuration is identical the default, except with a different ARN of course.  I have not modified the hello_worker.py yet (so it is also very basic).  I will try this on a different OS to check results.

Andrew

OS is Ubuntu 18.04, Python 3.6.6:

 stefuna --config=hello_config
2018-10-23 23:20:14,999 [INFO][MainProcess/20890] Running examples.hello_worker.HelloWorker for activity HelloExample arn:aws:states:us-east-1:754185987656:activity:Process_Imagery with 8 workers
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/stefuna", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/stefuna/stefuna.py", line 97, in main
    healthcheck=config['healthcheck'])
TypeError: 'NoneType' object is not callable

**Comment by andrew6850** [comment]
Same result on Amazon Linux 2 (Python 3.6.6), this time using the default files listed in the readme.  Will look deeper for a mistake I'm making somewhere.

Thanks,
Andrew

**Comment by irothschild** [comment]
Looks like it couldn't find the server class specified in your config. I should do a better job checking for that and showing an error.

**Comment by irothschild** [comment]
Fixed in https://github.com/irothschild/stefuna/pull/11
