### ISSUE TITLE
ImportError: cannot import name Server

### ISSUE THREAD

**Issue by knadigatla** [irothschild/stefuna#6]
Hello,
I was trying to test this module, facing below error when I try to run a simple worker/server.

Traceback (most recent call last):
  File "/Users/kiran/Documents/installs/python-virtenvs/aws-python27/bin/stefuna", line 7, in <module>
    from stefuna.stefuna import main
  File "/Users/kiran/Documents/installs/python-virtenvs/aws-python27/lib/python2.7/site-packages/stefuna/stefuna.py", line 5, in <module>
    from stefuna import Server, configure_logger  # noqa
ImportError: cannot import name Server

**Comment by irothschild** [comment]
Only Python 3.4 and above are supported.
